CREATE TABLE bull (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
name VARCHAR (120) NOT NULL,
race VARCHAR (120) NOT NULL,
owner VARCHAR (120) NOT NULL,
weight FLOAT NOT NULL,
agressivenessLevel INT NOT NULL
)
